spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  application:
    name: boying-user
  profiles:
    active: dev #默认为开发环境

#dao下放置mbg不能自动生成的一些xml文件
#- classpath*:com/**/mapper/*.xml 代表了扫描所有组件下的mapper,即扫描了mbg的
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: boying-user-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7) 7天过期
  tokenHead: 'Bearer '  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /user/**
      - /home/**

# 自定义redis key
redis:
  database: boying
  key:
    authCode: 'authCode'
    user: 'user'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

